spring.application.name=ecommerce-api


# 1. C?u hình ???ng d?n k?t n?i ??n MySQL (Thay 'ecommerce_db' b?ng tên Database c?a b?n)
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
# Thay '1234' b?ng m?t kh?u MySQL Workbench/XAMPP c?a b?n
spring.datasource.password=1234

# 2. C?u hình Hibernate (JPA) ?? t? ??ng t?o b?ng t? code Java vào MySQL
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect